export const CHANGE_MODE = "CHANGE_MODE";
export const OBTAIN_COUNTRIES = "OBTAIN_COUNTRIES";
export const FILTER_COUNTRIES = "FILTER_COUNTRIES";
export const INFO_COUNTRY = "INFO_COUNTRY";
export const CLEAN_INFO_COUNTRY = "CLEAN_INFO_COUNTRY";
